#
# Exception
#

class LogicError(Exception):
    pass

class IOError(Exception):
    pass

